### ISSUE TITLE
Where is the es-geonames Dockerfile?

### ISSUE THREAD

**Issue by chilland** [openeventdata/mordecai#11]
Is the Dockerfile for the `openeventdata/es-geonames` image publicly available in a github repo?

**Comment by ahalterman** [comment]
I don't have one. I think it got left behind at Caerus. I've been meaning to rebuild the index with an updated geonames dump, so I can put a Dockerfile together then. Question: should it download the dump and do the ES indexing in the Dockerfile, or pull a prebuilt ES index from S3?

Andy

**Comment by chilland** [comment]
Ah thats what I figured. Definitely just use the ES docker image and mount the index as a volume.

**Comment by ahalterman** [comment]
Move discussion to https://github.com/openeventdata/es-geonames
