### ISSUE TITLE
no module named mitie error

### ISSUE THREAD

**Issue by cliffnyang** [openeventdata/mordecai#13]
i'm getting an "importError" when i run the `app.py` after running `docker-compose up -d`. any idea how to fix this? i'm using a mac.

**Comment by ahalterman** [comment]
Hmm, it should be installed with `pip install -r requirements.txt` (and now that I look at it, also through `pip install git+...`). I'm hoping to merge PR #2 in tomorrow or the next day. Can you check if that branch resolves your issue? After you checkout the branch, you can check if it runs with 

```
sudo docker build -t mordecai .
sudo docker run  mordecai python -c 'import mitie'
```

Let me know if that doesn't resolve it.
