### ISSUE TITLE
API changes

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/mordecai#22]
I'm considering breaking changes to the API (as part of a potential large release).

- each document-level request would return the Mordecai version number, the last updated date for the Elasticsearch index, and the language used. The place names would then be values in a "results" field.
- Each place name's data would also include the Geonames ID number, which would make it much easier to look up or match with evaluation sets.

**Comment by philip-schrodt** [comment]
I'm okay with this, and actually in the application I'm using, we get the Geonames ID and this would simplify things. Also the ID is unique, whereas text names often aren't.

**Comment by ahalterman** [comment]
Closed by PR #33.
