### ISSUE TITLE
mordecai service error

### ISSUE THREAD

**Issue by smalgireddy** [openeventdata/mordecai#24]
Actually I am trying to start the mordecai service with the docker command, but it is throwing below error.
{u'es_host': 'elastic',
 u'es_port': '9200',
 u'mitie_directory': '/usr/src/MITIE/mitielib',
 u'mitie_ner_model': '/usr/src/data/MITIE-models/english/ner_model.dat',
 u'mordecai_port': 5000,
 u'word2vec_model': '/usr/src/data/GoogleNews-vectors-negative300.bin.gz'}
Setting up MITIE.
Traceback (most recent call last):
  File "app.py", line 24, in <module>
    configs['mitie_ner_model'])
  File "/usr/src/resources/utilities.py", line 126, in setup_mitie
    ner_model = mitie.named_entity_extractor(mitie_ner_model)
  File "/src/mitie/mitie/mitie.py", line 181, in __init__
    raise Exception("Unable to load named entity extractor from " + filename)
Exception: Unable to load named entity extractor from /usr/src/data/MITIE-models/english/ner_model.dat

***************
can anybody suggest what could be the cause? and how to resolve it. thank you.
steps followed:
I built the mordecai as suggested in the doc, and tried to start with the image_id.

**Comment by ahalterman** [comment]
It looks like a problem when you're attaching the data. In the `sudo docker run -d -p 5000:5000 -v PATH/TO/data:/usr/src/data --link elastic:elastic mordecai` command, are you giving it the full and correct path to the downloaded data? `PATH/TO/data` should be something like `/home/andy/Downloads/data`.

**Comment by smalgireddy** [comment]
yes, that was my mistake. thank you for helping me out. It's working now :-)
