### ISSUE TITLE
Convert to Python package

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/mordecai#26]
Rather than being fundamentally a (Dockerized) REST service like version 1 was, version 2 will be an installable Python package, with a separate repo that packages and runs it as a service.

**Comment by philip-schrodt** [comment]
To paraphrase the inimitable Hal W. Hardenbergh's ca. 1982 remark on COBOL "Docker is necessary just as maggots are necessary, but we don't have to like either, and we don't." So...yea!
