### ISSUE TITLE
Different languages as inputs

### ISSUE THREAD

**Issue by Maryam-Imani** [openeventdata/mordecai#32]
Andy, does the new version of Mordecai work on different languages?

**Comment by ahalterman** [comment]
Not yet, but I'm designing Mordecai to make it easy to switch languages. The main component that needs to be changed is the spaCy model (exists for Spanish, working on it for Arabic). The country picking model was trained on English but should perform okay on other languages (but we'll see). I'm guessing a January time frame for other languages.
