### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by Maryam-Imani** [openeventdata/mordecai#45]
For some text such as the following text: 

>>> text= '''Santa Cruz is a first class municipality in the province of Davao del Sur, Philippines. It has a population of 81,093 people as of 2010. The Municipality of Santa Cruz is part of Metropolitan Davao. Santa Cruz is politically subdivided into 18 barangays. Of the 18 barangays, 7 are uplands, 9 are upland-lowland and coastal and 2 are lowland-coastal. Pista sa Kinaiyahan A yearly activity conducted every last week of April as a tribute to the Mother Nature through tree-growing, cleanup activities and Boulder Face challenge. Araw ng Santa Cruz It is celebrated every October 5 in commemoration of the legal creation of the municipality in 1884. Highlights include parades, field demonstrations, trade fairs, carnivals and traditional festivities. Sinabbadan Festival A festival of ethnic ritual and dances celebrated every September. Santa Cruz is accessible by land transportation vehicles plying the Davao-Digos City, Davao-Kidapawan City, Davao-Cotabato City, Davao-Koronadal City and Davao-Tacurong City routes passing through the town's single, 27 kilometres (17 mi) stretch of national highway that traverses its 11 barangays. From Davao City, the administrative center of Region XI, it is 38 kilometres (24 mi) away within a 45-minute ride, while it is 16 kilometres (9.9 mi) or about 15-minute ride from provincial capital city of Digos.
... '''

I got this error: 

>>> `out = geo.geoparse(text)`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/mordecai/geoparse.py", line 955, in geoparse
    all_tasks, sorted_meta, sorted_X = self.format_for_prodigy(X, meta, loc['word'], return_feature_subset=True)
  File "/usr/local/lib/python3.5/dist-packages/mordecai/geoparse.py", line 813, in format_for_prodigy
    sorted_X, sorted_meta = self.ranker(X, meta)
  File "/usr/local/lib/python3.5/dist-packages/mordecai/geoparse.py", line 781, in ranker
    sorted_meta = [meta[r] for r in ranks]
  File "/usr/local/lib/python3.5/dist-packages/mordecai/geoparse.py", line 781, in <listcomp>
    sorted_meta = [meta[r] for r in ranks]
IndexError: list index out of range

**Comment by ahalterman** [comment]
Can you `pip install --upgrade mordecai` and try again? I'm not getting the error.

**Comment by Maryam-Imani** [comment]
Thank you. It is working.

**Comment by ahalterman** [comment]
👍
