### ISSUE TITLE
using and customize elasticsearch geonames docker

### ISSUE THREAD

**Issue by domeniconappo** [openeventdata/mordecai#47]
Hi there,
I have problems in setting up an environment with docker compose. 

First, the geonames index is not automatically created by elasticsearch so I need to perform a curl PUT to create the index. Also, it seems that using docker compose and mapped volumes, there are issues with file permissions so there is need to perform some chmod/chown commands before to launch the ES server.

To do all above, I need to customize/override the ES docker entrypoint and command. but I'm having hard time and all kind of issues...in the best case, the docker simply exit with status code 0.

Also, I noticed that the docs are referring to an older version of Elasticsearch docker image (5.5.2 vs 6.2.2). The recent ones are not on community docker repo...Now ES has its own docker repository.

Is there anyone that is willing to share his docker compose configuration?
Thanks in advance,
d

**Comment by domeniconappo** [comment]
not strictly related to this project

**Comment by ahalterman** [comment]
👍 And FYI, if you're interested in the guts of the ES Docker container, it's all at this repo: https://github.com/openeventdata/es-geonames. For 5.5.2 vs. 6.2.2, I found the earlier one easier to pass arguments to when starting it, so I've kept the version set to that. Happy to answer issues at that repo (or here), and sorry for the delay in getting back.
