### ISSUE TITLE
Keep getting error when trying pip install mordecai

### ISSUE THREAD

**Issue by Xper1** [openeventdata/mordecai#49]
I'm running Python 3.6 and when I write "pip install mordecai" I keep getting a list of errors that say "Failed building wheel for ujson", "  Failed building wheel for preshed", "  Failed building wheel for cymem", etc.

I read here( "https://stackoverflow.com/questions/43370851/failed-building-wheel-for-spacy") that i need to install spacy first but when I pip install spacy I again get "Failed building wheel for ujson", "  Failed building wheel for preshed", "  Failed building wheel for cymem", etc.

What should I do?

**Comment by Xper1** [comment]
Ok, perhaps I should also mention that I'm using a Mac, v. 10.13.4

**Comment by ahalterman** [comment]
Reading the rest of that page, it sounds like it might be a problem with your compiler/devtools. What happens if you update your XCode command line tools?
