### ISSUE TITLE
Not able to install Geonames gazetteer running in Elasticsearch

### ISSUE THREAD

**Issue by Xper1** [openeventdata/mordecai#50]
Hi, I typed docker pull elasticsearch:5.5.2 as per the instructions and got the following response:
5.5.2: Pulling from library/elasticsearch
Digest: sha256:3686a5757ed46c9dbcf00f6f71fce48ffc5413b193a80d1c46a21e7aad4c53ad
Status: Image is up to date for elasticsearch:5.5.2

But then when I type "wget https://s3.amazonaws.com/ahalterman-geo/geonames_index.tar.gz --output-file=wget_log.txt" I got "-bash: wget: command not found". Did I miss something?

**Comment by ahalterman** [comment]
Ahh, sorry, the instructions assume wget is already installed. Now that you've installed Homebrew, you should be able to just run `brew install wget` and try it again.

**Comment by Xper1** [comment]
Ok, thank you. It looks like everything but the last line loaded . 

For the last line I wrote:docker run -d -p 127.0.0.1:9200:9200 -v $(pwd)/geonames_index/:/usr/share/elasticsearch/data elasticsearch:5.5.2 and the response was:

e91cc6b49d954fbd7376388e10e1bbfc92f675d108fed76dbd5ad6e7dc3a10f3
docker: Error response from daemon: driver failed programming external connectivity on endpoint objective_zhukovsky (b2b9a87db50fb2748a372b32922e9def4201bdcd5bf7a2f2613490884520b67c): Bind for 127.0.0.1:9200 failed: port is already allocated.
