### ISSUE TITLE
Spans for extracted placenames incorrectly start at 0

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/mordecai#53]
All spans returned by Mordecai begin at 0, which is incorrect. E.g.

```
geo.geoparse("""The state of North Rhine-Westphalia ranks first in population among 
German states for both Roman Catholics and Protestants.""")

{...
'spans': [{'end': 22, 'start': 0}],
...}
```

**Comment by vlurgio** [comment]
Yeah i'm getting both start and end spans that are completely wrong. 
[{'word': 'Jollibee',
  'spans': [{'start': 0, 'end': 8}],
  'country_predicted': 'PHL',
  'country_conf': 0.93927664},
 {'word': 'Jollibee',
  'spans': [{'start': 0, 'end': 8}],
  'country_predicted': 'PHL',
  'country_conf': 0.93927664},
 {'word': 'Metro Manila',
  'spans': [{'start': 0, 'end': 12}],
  'country_predicted': 'PHL',
  'country_conf': 0.9998105,
  'geo': {'admin1': 'Metro Manila',
   'lat': '14.57775',
   'lon': '121.04599',
   'country_code3': 'PHL',
   'geonameid': '7521311',
   'place_name': 'National Capital Region',
   'feature_class': 'A',
   'feature_code': 'ADM1'}}]

**Comment by ahalterman** [comment]
This is a result of disabling the dependency parser for speed. spaCy uses the dependency parse to find sentence splits, so without the dependency parse, we can't get good sentence boundaries and that messes up the offsets. (There's a basic rule-based sentence splitter, but it doesn't work well for me). Here are the two options:

1. Add the dependency parser, which gives sentence splits but takes about twice as long as the NER only on 5,000 long documents:

```
0m34.324s  (ner only)
1m9.149s   (ner, dep)
1m25.417s  (ner, dep, tagger)
```

2. Use documents, rather than sentences, as the main unit of text. This might be better anyway, since all of Mordecai's training data is sentence-level. The major downside is that if people pass large documents in, all the text will be duplicated in every result and the offsets will be large.

Since I'm really trying to improve the speed right now, I'm more inclined to go with option 2.
