### ISSUE TITLE
bulk_geoparse returns no 'geo' keys

### ISSUE THREAD

**Issue by jamesmbell** [openeventdata/mordecai#62]
When I run batch_geoparse on a short list of strings, I get 0s for all country_conf values and no 'geo' keys/values.

```
from mordecai import Geoparser
geo = Geoparser()
ss=["I traveled from Oxford to Ottawa.","I visited New Orleans."]
geo.batch_geoparse(ss)

[[{'word': 'Oxford',
   'spans': [{'start': 0, 'end': 6}],
   'country_predicted': '',
   'country_conf': 0},
  {'word': 'Ottawa',
   'spans': [{'start': 0, 'end': 6}],
   'country_predicted': '',
   'country_conf': 0}],
 [{'word': 'New Orleans',
   'spans': [{'start': 0, 'end': 11}],
   'country_predicted': '',
   'country_conf': 0}]]
```

Likewise, I've been unable to finish running geoparse on a single string. I've tried running the example usage code (i.e. `geo.geoparse("I traveled from Oxford to Ottawa.")`), but it produces no output after >30 minutes.

Any thoughts about what might be causing this behavior?

FYI, I'm running this code on a Mac laptop with an i7 processor and 16GB of RAM. When installing mordecai and elasticsearch, I copied and pasted the directions in the README.md, and I'm running all code from within the same directory.

**Comment by jamesmbell** [comment]
query_geonames runs quickly and returns ~50 hits 

```
{'hits': {'hits': [{'admin1_code': '01',
    'admin2_code': '',
    'admin3_code': '',
    'admin4_code': '',
    'alternativenames': [''],
    'asciiname': 'Oxford',
    'cc2': '',
    'coordinates': '53.62209,-113.54782',
    'country_code2': 'CA',
    'country_code3': 'CAN',
    'dem': '677',
    'elevation': '',
    'feature_class': 'P',
    'feature_code': 'PPLX',
    'geonameid': '7626871',
    'modification_date': '2018-06-05',
    'name': 'Oxford',
    'population': '0',
    'timezone': 'America/Edmonton'},
   {'admin1_code': '26',
    'admin2_code': '4215802',
    'admin3_code': '',
    'admin4_code': '',
    'alternativenames': [''],
    'asciiname': 'Oxford',
    'cc2': '',
    'coordinates': '-26.23333,-49.4',
    'country_code2': 'BR',
    'country_code3': 'BRA',
    'dem': '831',
    'elevation': '',
    'feature_class': 'P',
    'feature_code': 'PPL',
    'geonameid': '3455646',
    'modification_date': '2018-06-05',
    'name': 'Oxford',
    'population': '0',
    'timezone': 'America/Sao_Paulo'},
...
```

**Comment by ahalterman** [comment]
Thanks, that's very useful. I can take a deeper look at it tomorrow afternoon and I'll see what I can figure out.

**Comment by jamesmbell** [comment]
It's probably worth noting that the geo.infer_countries("...") also hangs. After running that function line by line, it appears to get stuck at `prediction = geo.country_model.predict(i['matrix']).transpose()[0]` (line 701 of geoparse.py).

Perhaps this has something to do with my tensorflow setup? I'll look into that next. Otherwise, let me know if you think of anything else in the meantime. Thanks for your help!

**Comment by jamesmbell** [comment]
It appears that this may be an OSX specific issue. Looking back through my terminal output, I noticed the following:

```
OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized.
OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
```

I'm not sure how this happened, but I suspect it has something to do with a mishandled dependency in Anaconda. Enabling the KMP_DUPLICATE_LIB_OK environment variable did resolve the hang up in Mordecai, though this isn't a permanent solution. Thanks again for your help! Feel free to close this issue.
