### ISSUE TITLE
"'nlp' is not defined"

### ISSUE THREAD

**Issue by organizejs** [openeventdata/mordecai#64]
I'm getting an issue when running a simple test script
```python
from mordecai import Geoparser
geo = Geoparser()
geo.geoparse("From Ottowa to Beijing.")
```

This is the error:
![image](https://user-images.githubusercontent.com/25647759/51279192-a97a2580-19aa-11e9-9858-86c1302f603f.png)

**Comment by ahalterman** [comment]
Which version of spaCy are you running? I just tried with 2.0.16 and it worked.

**Comment by organizejs** [comment]
@ahalterman i'm using spaCy version: 2.0.18
Let me downgrade and try again

**Comment by organizejs** [comment]
i downgraded  and i'm getting the exact same issue

**Comment by ahalterman** [comment]
Huh. Thanks for checking. What happens if you explicitly create the `nlp` object before calling Mordecai? 

```
import spacy
nlp = spacy.load("en_core_web_lg")

# then load mordecai
from mordecai import Geoparser
geo = Geoparser()
geo.geoparse("From Ottowa to Beijing.")
```

**Comment by organizejs** [comment]
i get the same issue:
![image](https://user-images.githubusercontent.com/25647759/51336067-abe38a80-1a51-11e9-93bd-d06d4c4266ac.png)

**Comment by organizejs** [comment]
any chance it might be numpy version related?

**Comment by ahalterman** [comment]
It looks like an issue with your spaCy installation. [This issue](https://github.com/explosion/spaCy/issues/2312) seems to be the same and was solved by a fresh install.

You could also take a look at spacy's `validate` command, which checks whether the models are compatible with your current version: https://spacy.io/api/cli#validate

**Comment by organizejs** [comment]
Thanks i'll try out a fresh install and keep you posted.

**Comment by organizejs** [comment]
Looks like re-creating the virtual env worked. Thanks

**Comment by ahalterman** [comment]
Happy to help!

**Comment by wangjiqing1** [comment]
@organizejs  您好，请问你成功运行的环境spacy版本号是多少？还有这个en_core_web_lg
