### ISSUE TITLE
batch_geoparse returns no country prediction information

### ISSUE THREAD

**Issue by edwardcqian** [openeventdata/mordecai#65]
Similar result as #62. When `batch_geoparse` is ran it will return empty country prediction information.

However, if any `geoparse` is run before running `batch_geoparse`, `batch_geoparse` will behaviour as expected.

**Comment by ahalterman** [comment]
Thanks for the report and the info that running without batch first fixes it. I’ll take a look.

**Comment by ahalterman** [comment]
I can't replicate the issue using the latest version (2.0.3). Let me know if the issue persists after upgrading.
