### ISSUE TITLE
Altering/Restricting GeoNames Gazetteer?

### ISSUE THREAD

**Issue by drtfraser** [openeventdata/mordecai#67]
My understanding is that Mordecai uses the GeoNames Gazetteer in Elasticsearch to lookup locations/places.  I'm am planning to use Mordecai for parsing documents where I only want City, Region, and Country information.  I know I can filter Mordecai's predictions after the fact, but ideally I'd like to exclude certain feature_classes before it even makes predictions.

Is there a straightforward way to do this?  I know that through the GeoNames website one can download data on cities above a certain size, which would fit my needs.  However, what isn't clear to me is how I would go about altering the geonames_index folder that is part of the install instructions in order to do so.  

Sorry - this is less an issue than a question.

**Comment by ahalterman** [comment]
The code that I used to create the Elasticsearch Geonames index is in this repo: https://github.com/openeventdata/es-geonames. If you wanted to exclude certain types of features from the index, you could do it pretty easily by inserting some sort of `if` check around [here](https://github.com/openeventdata/es-geonames/blob/master/geonames_elasticsearch_loader.py#L89).
