### ISSUE TITLE
Running "docker pull elasticsearch:5.5.2" returns error

### ISSUE THREAD

**Issue by RanaBan** [openeventdata/mordecai#71]
The error is:

Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp 127.16.199.20:8080: connect: connection refused

How to get elasticsearch?

**Comment by ahalterman** [comment]
This sounds like it might be an issue with your local network/proxies. Are you able to get other images? E.g. `docker pull ubuntu:14.04`?

**Comment by RanaBan** [comment]
"docker pull ubuntu:14.04" gives
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Yes it is due to proxy. When I have tried it through my mobile phone connection it started downloading. But from institute connection it is not happening. I need to do this behind the proxy. 
I have created the "~/.docker/config.json " as given, but then also it is not working behind the proxy.
There are instructions about setting environment variables. I am new in docker so after trying a lot I could not set the ENVs. 
Can you tell me how I can set the ENVs to pull elasticsearch

**Comment by ahalterman** [comment]
Hmm, it's a bit hard to figure out how to get around the proxy without being there. I'd suggest one of two things: (1) VPNing out of your network and seeing if the VPN connection bypasses whatever the proxy is doing, or (2) talking to someone at your institute about what the proxy is doing and whether you can get around it.

**Comment by RanaBan** [comment]
It was working well. Found a new error today on running geo = Geoparser()
"NotFoundError: TransportError(404, 'index_not_found_exception', 'no such index')"

**Comment by ahalterman** [comment]
That sounds like an issue with how you're starting the container. Can you see which indices are running in ES? Are you sure you've given it the right path to the downloaded index when you start the container?

**Comment by RanaBan** [comment]
I have restarted the computer and started ES by "docker run ..." command, then mordecai worked. Don't know why but after a restart it started working. Now it is fine, if any further issue comes I will ask here.
