### ISSUE TITLE
Mordecai Install with Anaconda Python on Windows 10

### ISSUE THREAD

**Issue by rrwen** [openeventdata/mordecai#73]
I had some trouble installing `mordecai` with Python's `pip` on Windows, so I did some troubleshooting, resolved some package version clashing, and finally had a working solution documented here:

https://github.com/ryerson-ggl/mordecai-geoparser-on-windows

This might help others who need some more detailed instructions for installing `mordecai` (at least for version `mordecai-2.0.1.post1`).

**Comment by ahalterman** [comment]
This is very helpful! Thank you very much.
