### ISSUE TITLE
Errors in train_country_model.py

### ISSUE THREAD

**Issue by sreejith-ms** [openeventdata/mordecai#78]
Hi,

Not able to run train_country_model.py

![image](https://user-images.githubusercontent.com/13817581/82531484-1ed8a600-9b5d-11ea-92e0-880e746ecf79.png)

`with jsonlines.open('geo_annotated/geo_country_db.jsonl') as reader:`

The file geo_country_db.jsonl is not found.

Also please share the training scripts for rank model.

**Comment by ahalterman** [comment]
The models are trained on texts that can't be shared for licensing/copyright reasons, unfortunately. I've uploaded the ranker training script in the `retrain` branch and will merge in once it passes all the tests.
