### ISSUE TITLE
Getting initialization error

### ISSUE THREAD

**Issue by monalipawar** [openeventdata/mordecai#86]
![image](https://user-images.githubusercontent.com/65918077/98056351-bb41ec80-1e0d-11eb-8146-bca7a8d67062.png)

**Comment by monalipawar** [comment]
After I modified my module versions , error got changed
![image](https://user-images.githubusercontent.com/65918077/98063805-e254ea00-1e1e-11eb-832e-3b45d35df450.png)

**Comment by monalipawar** [comment]
My requirement.txt
![image](https://user-images.githubusercontent.com/65918077/98063850-f7ca1400-1e1e-11eb-9724-2d8053f05b75.png)

**Comment by ainkov** [comment]
Hey @monalipawar , this helped: https://stackoverflow.com/a/64635871

**Comment by monalipawar** [comment]
I am happy to inform that my issue has been fixed . It was few modules version compatibility issue . I gave the specific versions of modules and it worked !! 
![image](https://user-images.githubusercontent.com/65918077/98566294-95d53880-227c-11eb-9300-ca6bd2c02ac9.png)

**Comment by monalipawar** [comment]
> Hey @monalipawar , this helped: https://stackoverflow.com/a/64635871

Thanks so much for your response. Above fix worked for me .
