### ISSUE TITLE
Custom gazetteer

### ISSUE THREAD

**Issue by jayrobwilliams** [openeventdata/mordecai#96]
Is there any way to specify a custom gazetteer instead of the local geonames instance? I know #67 touched on filtering the types of feature classes used for the search, but would it be possible to use a totally different gazetteer? I'm thinking specifically about the feasibility of creating a gazetteer from historical geographic data for archival research.

**Comment by ahalterman** [comment]
This is a little tricky to do because there are a lot of assumptions built in to the code about how the gazetteer is structured and how it is loaded into Elasticsearch. Do you have a link to the custom gazetteer that you're thinking of using?

**Comment by jayrobwilliams** [comment]
Ah. No, this was a thought about a far off potential project. I'll check back in and reopen this issue if the project ever gets any closer to reality.
